name: Build Go app and push to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Copy static template files
      run: xcopy /i templates build\templates
    
    - name: Copy static template files
      run: xcopy /i templates/assets build\templates\assets
      
    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Test
      run: go test

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v1
      
      with:
        credentials: ${{ secrets.azureprofile }}

        # Name of the Azure Web App
        app-name: simca
        
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: build/
        publish-profile: ${{ secrets.azureprofile }}
